version: "3.7"
services: 
  sentinel:
    container_name: sentinel
    build: 
      context: .
      args: 
        JAR_FILE: sentinel-dashboard-${JAR_VERSION:-1.7.1}.jar
      dockerfile: Dockerfile
    image: alibaba_sentinel:${JAR_VERSION:-1.7.1}
    env_file: env/env
    ports: 
      - 7777:7777
    restart: on-failure:3
    networks: 
      - sentinel-net
networks: 
  sentinel-net:
    driver: bridge
